bases:
- ../rbac-namespace-default
- ../kafka
- ../zookeeper
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
  path: fsgroup-65534.yaml
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pzoo
  path: fsgroup-65534.yaml
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: zoo
  path: fsgroup-65534.yaml
# https://github.com/kubernetes-sigs/kustomize/issues/915#issuecomment-477808963
patchesStrategicMerge:
- nonroot-image-kafka.yaml
- nonroot-image-zookeeper.yaml
