apiVersion: v1
data:
  kafka_server_jaas.conf: |
    KafkaServer {
       org.apache.kafka.common.security.plain.PlainLoginModule required
       serviceName="server"
       username="admin"
       password="admin-secret"
       user_admin="admin-secret"
       user_client="client-secret"
       sasl.mechanism=PLAIN
       security.protocol=SASL_PLAINTEXT;

       org.apache.kafka.common.security.scram.ScramLoginModule required
       serviceName="server"
       username="admin"
       password="admin-secret"
       user_admin="admin-secret"
       user_client="client-secret"
       sasl.mechanism=SCRAM-SHA-256
       security.protocol=SASL_PLAINTEXT;
    };
    Client {
    };
kind: ConfigMap
metadata:
  name: kafka-jaas-config
  namespace: kafka

