apiVersion: v1
data:
  kafka_server_jaas.conf: |
    KafkaServer {
       org.apache.kafka.common.security.plain.PlainLoginModule required
       serviceName="server"
       username="admin"
       password="admin-secret"
       user_admin="admin-secret"
       user_client="client-secret";
    };
    Client {
    };
kind: ConfigMap
metadata:
  name: kafka-jaas-config
  namespace: kafka

